### ISSUE TITLE
Operation risk in com.pojosontheweb:monte-repack:1.1

### ISSUE THREAD

**Issue by SOUJANYAPULIGILLA** [pojosontheweb/selenium-utils#37]
We wanted to bring to your attention that during the industry-standard security scan in our frameworks, a potential operational risk was detected in the javax.media.jai:com.springsource.javax.media.jai.core:1.1.3 library. This library is a transitive dependency used by com.pojosontheweb:monte-repack:1.1. To mitigate this risk, we are actively investigating the issue and working identifying a newer version of com.pojosontheweb:monte-repack that addresses the identified security concern. Our priority is to ensure the security and reliability of our software. We request you to please provide a newer version of vulnerable free library or please let us know if you have any plan to address these vulnerabilities from the transitive dependencies ?.

**Comment by vankeisb** [comment]
Hi,
Sorry for the delay.
We have no plans to upgrade this.This repackaged "monte media" is used to optionally record webtests. You can use something else if you want (e.g. ffmpeg).
